import { NextIntlClientProvider } from 'next-intl'
import type { Metadata } from "next";
import "./globals.css";
import { routing } from '@/i18n/routing'
import { notFound } from 'next/navigation'
import { getMessages } from 'next-intl/server';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {

  const { locale } = await params;

if (!routing.locales.includes(locale as any)) {
  notFound()
}
  return (
    <html lang={locale}>
    <body className="min-h-full flex flex-col">
      <NextIntlClientProvider messages={await getMessages()}>
          {children}
        </NextIntlClientProvider>
        </body>
    </html>
  );
}
